version: "3.9"
services:
  hut-postgres:
    image: postgres:14-alpine
    container_name: hut-postgres
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: alpinehut_db
    hostname: hut-postgres
    restart: unless-stopped
    volumes:
      - ./data/postgres:/var/lib/postgresql/data:rw
    ports:
      - "15432:5432"
    networks:
      - hut
  hut-nx:
    build:
      context: .
      target: base-hut
    environment:
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: alpinehut_db
      DEV_PLATFORM: DOCKER
      USE_STUB_HARDWARE: true
    container_name: hut-nx
    entrypoint: ["/www/entrypoint-dev.sh"]
    volumes:
      - .:/www:delegated
    ports:
      - "4200:4200"
      - "3333:3333"
      - "9229:9229"
    networks:
      - hut
    depends_on:
      - hut-postgres
networks:
  hut:
    external: true
